### PR TITLE
Update session 6 - fix syntax highlighting and update Dockerfiles to 2.2

### PR DESCRIPTION
**Pull request by natemcmaster**
* Replace docker hub with MCR (see https://hub.docker.com/_/microsoft-dotnet-core)
* Update to 2.2 images
* Use correct syntax highlighting
* Remove HTTPS internal ports (there is no cert inside a Docker container)

@davidfowl

### CODE REVIEW

**Comment by natemcmaster** [comment]
:bell:

**Review by spboyer — APPROVED** [review]

**Comment by spboyer** [comment]
@natemcmaster - thanks for the update! All good. One question, why the port change?

```
      - "5001:80" ->  - "5002:80"
```

Needed, preference, or requirement?

**Comment by natemcmaster** [comment]
When running a local web app, 5001 is the default port aspnet chooses for HTTPS. My browser had this cached and kept trying to load the website over HTTPS, which of course didn't work. Had to clear my localhost redirect cache to make it work

**Comment by spboyer** [comment]
I am not a fan of the 5000 series ports, Apple has known/and unknown products that caused quite a bit of time loss. iTunes has been known to select 5000-5001 in the past as well. We should consider using other ports. @davidfowl 

https://support.apple.com/en-us/HT202944

**Comment by natemcmaster** [comment]
Thanks for the review approval. I don't have write permissions, so someone else will have to merge.

**Pull request merged**
